INFO 2025-03-10 01:54:31,846 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 01:54:40,224 autoreload D:\Projects\FloodMonitoring\flood_monitoring\flood_monitoring\settings.py changed, reloading.
INFO 2025-03-10 01:54:42,232 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 01:55:14,724 basehttp "GET / HTTP/1.1" 200 1011
INFO 2025-03-10 01:55:14,798 basehttp "GET /static/js/flood.js HTTP/1.1" 304 0
INFO 2025-03-10 01:55:14,873 views in get_stations views
INFO 2025-03-10 01:55:17,319 basehttp "GET /stations/ HTTP/1.1" 200 3657210
INFO 2025-03-10 01:55:21,840 basehttp "GET /readings/E8266/ HTTP/1.1" 200 142503
INFO 2025-03-10 01:56:03,489 autoreload D:\Projects\FloodMonitoring\flood_monitoring\flood_monitoring\settings.py changed, reloading.
INFO 2025-03-10 01:56:05,521 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 01:56:09,589 basehttp "GET / HTTP/1.1" 200 1011
INFO 2025-03-10 01:56:10,891 basehttp "GET /stations/ HTTP/1.1" 200 3657210
INFO 2025-03-10 01:56:21,692 basehttp "GET /readings/1771TH/ HTTP/1.1" 200 143426
INFO 2025-03-10 01:57:15,957 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py changed, reloading.
INFO 2025-03-10 01:57:18,090 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 01:57:40,435 basehttp "GET / HTTP/1.1" 200 1011
INFO 2025-03-10 01:57:43,641 basehttp "GET /stations/ HTTP/1.1" 200 3657210
INFO 2025-03-10 01:57:46,044 basehttp "GET /readings/E1147 HTTP/1.1" 301 0
INFO 2025-03-10 01:57:47,068 basehttp "GET /readings/E1147/ HTTP/1.1" 200 142297
INFO 2025-03-10 01:59:38,184 autoreload D:\Projects\FloodMonitoring\flood_monitoring\flood_monitoring\settings.py changed, reloading.
INFO 2025-03-10 01:59:40,156 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 01:59:43,868 basehttp "GET / HTTP/1.1" 200 1011
INFO 2025-03-10 01:59:43,936 basehttp "GET /static/js/flood.js HTTP/1.1" 304 0
INFO 2025-03-10 01:59:44,005 views in get_stations - in views
INFO 2025-03-10 01:59:45,800 basehttp "GET /stations/ HTTP/1.1" 200 3657210
INFO 2025-03-10 01:59:48,842 basehttp "GET /readings/E70039 HTTP/1.1" 301 0
INFO 2025-03-10 01:59:48,899 views in get_station_readings - in views
INFO 2025-03-10 01:59:51,609 basehttp "GET /readings/E70039/ HTTP/1.1" 200 152603
INFO 2025-03-10 02:01:00,946 autoreload D:\Projects\FloodMonitoring\flood_monitoring\flood_monitoring\settings.py changed, reloading.
INFO 2025-03-10 02:01:02,741 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 02:01:16,430 basehttp "GET / HTTP/1.1" 200 1011
INFO 2025-03-10 02:01:16,564 views in get_stations - in views
INFO 2025-03-10 02:01:18,011 basehttp "GET /stations/ HTTP/1.1" 200 3657210
INFO 2025-03-10 02:44:33,781 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py changed, reloading.
INFO 2025-03-10 02:44:35,086 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 02:54:42,824 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 02:55:29,264 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\stationModel.py changed, reloading.
INFO 2025-03-10 02:55:30,214 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 02:55:41,570 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\readingModel.py changed, reloading.
INFO 2025-03-10 02:55:42,724 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 02:56:16,566 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py changed, reloading.
INFO 2025-03-10 02:56:17,622 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 02:56:50,225 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py changed, reloading.
INFO 2025-03-10 02:56:51,214 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 02:56:57,954 basehttp "GET / HTTP/1.1" 200 1011
INFO 2025-03-10 02:56:58,040 basehttp "GET /static/js/flood.js HTTP/1.1" 304 0
ERROR 2025-03-10 02:56:58,208 log Internal Server Error: /stations/
Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 15, in get_stations
    stations = stationService.get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StationService.get_stations() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 19, in get_stations
    logger.error(f"{constants.GENERIC_ERROR} : {e}")
                    ^^^^^^^^^
NameError: name 'constants' is not defined
ERROR 2025-03-10 02:56:58,227 basehttp "GET /stations/ HTTP/1.1" 500 70973
INFO 2025-03-10 02:57:11,590 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py changed, reloading.
INFO 2025-03-10 02:57:12,776 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 02:57:16,461 basehttp "GET / HTTP/1.1" 200 1011
ERROR 2025-03-10 02:57:16,606 views Error: : StationService.get_stations() takes 0 positional arguments but 1 was given
ERROR 2025-03-10 02:57:16,695 log Internal Server Error: /stations/
Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 15, in get_stations
    stations = stationService.get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StationService.get_stations() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 20, in get_stations
    return JsonResponse({"An error accured in view get_station(): "}, status = 500)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2025-03-10 02:57:16,707 basehttp "GET /stations/ HTTP/1.1" 500 76130
INFO 2025-03-10 03:01:36,256 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:01:39,792 basehttp "GET / HTTP/1.1" 200 1011
ERROR 2025-03-10 03:01:39,919 views Error: : StationService.get_stations() takes 0 positional arguments but 1 was given
ERROR 2025-03-10 03:01:40,010 log Internal Server Error: /stations/
Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 15, in get_stations
    stations = stationService.get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StationService.get_stations() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 20, in get_stations
    return JsonResponse({"An error accured in view get_station(): "}, status = 500)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2025-03-10 03:01:40,024 basehttp "GET /stations/ HTTP/1.1" 500 76130
INFO 2025-03-10 03:03:51,063 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\stationModel.py changed, reloading.
INFO 2025-03-10 03:03:52,105 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:04:03,369 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\readingModel.py changed, reloading.
INFO 2025-03-10 03:04:04,974 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:04:06,212 basehttp "GET / HTTP/1.1" 200 1011
ERROR 2025-03-10 03:04:06,356 views Error: : StationService.get_stations() takes 0 positional arguments but 1 was given
ERROR 2025-03-10 03:04:06,463 log Internal Server Error: /stations/
Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 15, in get_stations
    stations = stationService.get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StationService.get_stations() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 20, in get_stations
    return JsonResponse({"An error accured in view get_station(): "}, status = 500)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2025-03-10 03:04:06,476 basehttp "GET /stations/ HTTP/1.1" 500 76130
INFO 2025-03-10 03:05:33,496 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py changed, reloading.
INFO 2025-03-10 03:05:34,548 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:05:38,874 basehttp "GET / HTTP/1.1" 200 1011
ERROR 2025-03-10 03:05:38,992 views Error: : StationService.get_stations() takes 0 positional arguments but 1 was given
ERROR 2025-03-10 03:05:39,104 log Internal Server Error: /stations/
Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 15, in get_stations
    stations = stationService.get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StationService.get_stations() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 20, in get_stations
    return JsonResponse({"An error accured in view get_station(): "}, status = 500)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2025-03-10 03:05:39,183 basehttp "GET /stations/ HTTP/1.1" 500 76166
INFO 2025-03-10 03:05:57,230 autoreload Watching for file changes with StatReloader
WARNING 2025-03-10 03:06:01,333 log Not Found: /monitor/
WARNING 2025-03-10 03:06:01,335 basehttp "GET /monitor/ HTTP/1.1" 404 3012
INFO 2025-03-10 03:06:07,622 basehttp "GET / HTTP/1.1" 200 1011
ERROR 2025-03-10 03:06:07,758 views Error: : StationService.get_stations() takes 0 positional arguments but 1 was given
ERROR 2025-03-10 03:06:07,828 log Internal Server Error: /stations/
Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 15, in get_stations
    stations = stationService.get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StationService.get_stations() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 20, in get_stations
    return JsonResponse({"An error accured in view get_station(): "}, status = 500)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2025-03-10 03:06:07,844 basehttp "GET /stations/ HTTP/1.1" 500 76166
INFO 2025-03-10 03:06:09,242 basehttp "GET / HTTP/1.1" 200 1011
ERROR 2025-03-10 03:06:09,351 views Error: : StationService.get_stations() takes 0 positional arguments but 1 was given
ERROR 2025-03-10 03:06:09,430 log Internal Server Error: /stations/
Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 15, in get_stations
    stations = stationService.get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StationService.get_stations() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 20, in get_stations
    return JsonResponse({"An error accured in view get_station(): "}, status = 500)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2025-03-10 03:06:09,443 basehttp "GET /stations/ HTTP/1.1" 500 76166
INFO 2025-03-10 03:06:09,895 basehttp "GET / HTTP/1.1" 200 1011
ERROR 2025-03-10 03:06:10,013 views Error: : StationService.get_stations() takes 0 positional arguments but 1 was given
ERROR 2025-03-10 03:06:10,082 log Internal Server Error: /stations/
Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 15, in get_stations
    stations = stationService.get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StationService.get_stations() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 20, in get_stations
    return JsonResponse({"An error accured in view get_station(): "}, status = 500)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2025-03-10 03:06:10,090 basehttp "GET /stations/ HTTP/1.1" 500 76166
INFO 2025-03-10 03:06:10,609 basehttp "GET / HTTP/1.1" 200 1011
ERROR 2025-03-10 03:06:10,728 views Error: : StationService.get_stations() takes 0 positional arguments but 1 was given
ERROR 2025-03-10 03:06:10,803 log Internal Server Error: /stations/
Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 15, in get_stations
    stations = stationService.get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StationService.get_stations() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 20, in get_stations
    return JsonResponse({"An error accured in view get_station(): "}, status = 500)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2025-03-10 03:06:10,818 basehttp "GET /stations/ HTTP/1.1" 500 76166
INFO 2025-03-10 03:12:07,562 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:12:12,687 basehttp "GET / HTTP/1.1" 200 1011
INFO 2025-03-10 03:12:12,760 basehttp "GET /static/js/flood.js HTTP/1.1" 304 0
ERROR 2025-03-10 03:12:12,816 views Error: : StationService.get_stations() takes 0 positional arguments but 1 was given
ERROR 2025-03-10 03:12:12,898 log Internal Server Error: /stations/
Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 15, in get_stations
    stations = stationService.get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StationService.get_stations() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 20, in get_stations
    return JsonResponse({"An error accured in view get_station(): "}, status = 500)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2025-03-10 03:12:12,908 basehttp "GET /stations/ HTTP/1.1" 500 76166
INFO 2025-03-10 03:13:43,131 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\service\stationService.py changed, reloading.
INFO 2025-03-10 03:13:45,101 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:13:49,294 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\service\readingService.py changed, reloading.
INFO 2025-03-10 03:13:50,646 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:14:06,378 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:14:11,030 basehttp "GET / HTTP/1.1" 200 1011
ERROR 2025-03-10 03:14:11,145 views Error: : StationService.get_stations() takes 0 positional arguments but 1 was given
ERROR 2025-03-10 03:14:11,225 log Internal Server Error: /stations/
Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 15, in get_stations
    stations = stationService.get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StationService.get_stations() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 20, in get_stations
    return JsonResponse({"An error accured in view get_station(): "}, status = 500)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2025-03-10 03:14:11,233 basehttp "GET /stations/ HTTP/1.1" 500 76166
INFO 2025-03-10 03:16:24,849 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\stationModel.py changed, reloading.
INFO 2025-03-10 03:16:26,170 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:16:33,850 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\readingModel.py changed, reloading.
INFO 2025-03-10 03:16:35,573 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:16:40,543 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\stationModel.py changed, reloading.
INFO 2025-03-10 03:16:41,702 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:17:20,275 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\service\stationService.py changed, reloading.
INFO 2025-03-10 03:17:21,424 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:18:03,687 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\service\stationService.py changed, reloading.
INFO 2025-03-10 03:18:05,030 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:18:09,337 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\service\readingService.py changed, reloading.
INFO 2025-03-10 03:18:10,617 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:18:25,522 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\service\stationService.py changed, reloading.
INFO 2025-03-10 03:18:27,069 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:18:56,838 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\readingModel.py changed, reloading.
INFO 2025-03-10 03:18:58,066 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:19:04,678 basehttp "GET / HTTP/1.1" 200 1011
ERROR 2025-03-10 03:19:04,838 views Error: : StationService.get_stations() takes 0 positional arguments but 1 was given
ERROR 2025-03-10 03:19:04,913 log Internal Server Error: /stations/
Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 15, in get_stations
    stations = stationService.get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StationService.get_stations() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 20, in get_stations
    return JsonResponse({"An error accured in view get_station(): "}, status = 500)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2025-03-10 03:19:04,927 basehttp "GET /stations/ HTTP/1.1" 500 76166
INFO 2025-03-10 03:19:28,533 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\readingModel.py changed, reloading.
INFO 2025-03-10 03:19:29,765 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:19:35,138 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\stationModel.py changed, reloading.
INFO 2025-03-10 03:19:36,337 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:19:40,899 basehttp "GET / HTTP/1.1" 200 1011
ERROR 2025-03-10 03:19:41,084 views Error: : StationService.get_stations() takes 0 positional arguments but 1 was given
ERROR 2025-03-10 03:19:41,166 log Internal Server Error: /stations/
Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 15, in get_stations
    stations = stationService.get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StationService.get_stations() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 20, in get_stations
    return JsonResponse({"An error accured in view get_station(): "}, status = 500)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2025-03-10 03:19:41,179 basehttp "GET /stations/ HTTP/1.1" 500 76166
INFO 2025-03-10 03:21:15,871 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\stationModel.py changed, reloading.
INFO 2025-03-10 03:21:17,032 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:21:25,272 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\stationModel.py changed, reloading.
INFO 2025-03-10 03:21:26,392 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:21:31,614 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\readingModel.py changed, reloading.
INFO 2025-03-10 03:21:32,858 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:22:32,537 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\service\readingService.py changed, reloading.
INFO 2025-03-10 03:22:33,785 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:22:51,604 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\service\readingService.py changed, reloading.
INFO 2025-03-10 03:22:52,762 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:22:56,682 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\service\readingService.py changed, reloading.
INFO 2025-03-10 03:22:57,835 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:23:23,580 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\service\stationService.py changed, reloading.
INFO 2025-03-10 03:23:24,775 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:23:31,594 basehttp "GET / HTTP/1.1" 200 1011
INFO 2025-03-10 03:23:31,664 basehttp "GET /static/js/flood.js HTTP/1.1" 304 0
ERROR 2025-03-10 03:23:31,757 views Error: : StationService.get_stations() takes 0 positional arguments but 1 was given
ERROR 2025-03-10 03:23:31,840 log Internal Server Error: /stations/
Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 15, in get_stations
    stations = stationService.get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StationService.get_stations() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 20, in get_stations
    return JsonResponse({"An error accured in view get_station(): "}, status = 500)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2025-03-10 03:23:31,854 basehttp "GET /stations/ HTTP/1.1" 500 76166
INFO 2025-03-10 03:25:11,216 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\stationModel.py changed, reloading.
INFO 2025-03-10 03:25:13,015 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:25:19,077 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\readingModel.py changed, reloading.
INFO 2025-03-10 03:25:20,561 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:25:27,486 basehttp "GET / HTTP/1.1" 200 1011
ERROR 2025-03-10 03:25:27,639 views Error: : StationService.get_stations() takes 0 positional arguments but 1 was given
ERROR 2025-03-10 03:25:27,729 log Internal Server Error: /stations/
Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 15, in get_stations
    stations = stationService.get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StationService.get_stations() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 20, in get_stations
    return JsonResponse({"An error accured in view get_station(): "}, status = 500)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2025-03-10 03:25:27,746 basehttp "GET /stations/ HTTP/1.1" 500 76166
INFO 2025-03-10 03:26:04,985 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\service\stationService.py changed, reloading.
INFO 2025-03-10 03:26:06,661 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:26:13,363 basehttp "GET / HTTP/1.1" 200 1011
INFO 2025-03-10 03:26:13,520 stationModel https://environment.data.gov.uk//flood-monitoring/id/stations
INFO 2025-03-10 03:26:14,848 basehttp "GET /stations/ HTTP/1.1" 200 3657654
ERROR 2025-03-10 03:26:19,041 views Error: : ReadingService.get_station_readings() takes 1 positional argument but 2 were given
ERROR 2025-03-10 03:26:19,096 log Internal Server Error: /readings/F1906/
Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 24, in get_station_readings
    station_readings = readingService.get_station_readings(station_id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ReadingService.get_station_readings() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\flood_monitoring\monitoring\views.py", line 29, in get_station_readings
    return JsonResponse({"An error accured in view get_station_readings(): "}, status = 500)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\FloodMonitoring\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2025-03-10 03:26:19,107 basehttp "GET /readings/F1906/ HTTP/1.1" 500 76482
INFO 2025-03-10 03:26:27,451 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\service\readingService.py changed, reloading.
INFO 2025-03-10 03:26:28,787 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:26:31,884 readingModel https://environment.data.gov.uk//flood-monitoring/id/stations/{station_id}/readings?_sorted
ERROR 2025-03-10 03:26:32,638 readingModel Error in fetching readings for station E1147: 400 Client Error: Bad Request for url: https://environment.data.gov.uk//flood-monitoring/id/stations/%7Bstation_id%7D/readings?_sorted
INFO 2025-03-10 03:26:32,641 basehttp "GET /readings/E1147/ HTTP/1.1" 200 23
INFO 2025-03-10 03:27:43,039 basehttp "GET /readings/720215 HTTP/1.1" 301 0
INFO 2025-03-10 03:27:43,098 readingModel https://environment.data.gov.uk//flood-monitoring/id/stations/{station_id}/readings?_sorted
ERROR 2025-03-10 03:27:43,650 readingModel Error in fetching readings for station 720215: 400 Client Error: Bad Request for url: https://environment.data.gov.uk//flood-monitoring/id/stations/%7Bstation_id%7D/readings?_sorted
INFO 2025-03-10 03:27:43,653 basehttp "GET /readings/720215/ HTTP/1.1" 200 23
INFO 2025-03-10 03:28:25,592 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\config.py changed, reloading.
INFO 2025-03-10 03:28:26,869 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:28:32,954 basehttp "GET / HTTP/1.1" 200 1011
INFO 2025-03-10 03:28:33,131 stationModel https://environment.data.gov.uk//flood-monitoring/id/stations/
INFO 2025-03-10 03:28:35,141 basehttp "GET /stations/ HTTP/1.1" 200 3657654
INFO 2025-03-10 03:28:39,332 readingModel https://environment.data.gov.uk//flood-monitoring/id/stations//{station_id}/readings?_sorted
ERROR 2025-03-10 03:28:40,293 readingModel Error in fetching readings for station 48143: 400 Client Error: Bad Request for url: https://environment.data.gov.uk//flood-monitoring/id/stations//%7Bstation_id%7D/readings?_sorted
INFO 2025-03-10 03:28:40,296 basehttp "GET /readings/48143/ HTTP/1.1" 200 23
INFO 2025-03-10 03:30:19,015 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\config.py changed, reloading.
INFO 2025-03-10 03:30:20,412 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:30:31,971 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\config.py changed, reloading.
INFO 2025-03-10 03:30:33,354 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:34:37,478 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\config.py changed, reloading.
INFO 2025-03-10 03:34:38,783 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:34:49,121 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\config.py changed, reloading.
INFO 2025-03-10 03:34:50,353 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:34:57,091 basehttp "GET / HTTP/1.1" 200 1011
INFO 2025-03-10 03:34:57,257 stationModel https://environment.data.gov.uk/flood-monitoring/id/stations
INFO 2025-03-10 03:34:58,762 basehttp "GET /stations/ HTTP/1.1" 200 3656752
INFO 2025-03-10 03:35:03,100 readingModel https://environment.data.gov.uk/flood-monitoring/id/stations/{station_id}/readings?_sorted
ERROR 2025-03-10 03:35:04,761 readingModel Error in fetching readings for station 720215: 400 Client Error: Bad Request for url: https://environment.data.gov.uk/flood-monitoring/id/stations/%7Bstation_id%7D/readings?_sorted
INFO 2025-03-10 03:35:04,765 basehttp "GET /readings/720215/ HTTP/1.1" 200 23
INFO 2025-03-10 03:37:26,136 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\config.py changed, reloading.
INFO 2025-03-10 03:37:27,452 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:39:36,771 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\readingModel.py changed, reloading.
INFO 2025-03-10 03:39:37,946 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:39:56,016 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\readingModel.py changed, reloading.
INFO 2025-03-10 03:39:57,317 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:40:01,451 autoreload D:\Projects\FloodMonitoring\flood_monitoring\monitoring\model\readingModel.py changed, reloading.
INFO 2025-03-10 03:40:02,612 autoreload Watching for file changes with StatReloader
INFO 2025-03-10 03:40:07,210 basehttp "GET / HTTP/1.1" 200 1011
INFO 2025-03-10 03:40:07,281 basehttp "GET /static/js/flood.js HTTP/1.1" 304 0
INFO 2025-03-10 03:40:07,394 stationModel https://environment.data.gov.uk/flood-monitoring/id/stations
INFO 2025-03-10 03:40:11,442 basehttp "GET /stations/ HTTP/1.1" 200 3656752
INFO 2025-03-10 03:40:14,415 readingModel https://environment.data.gov.uk/flood-monitoring/id/stations/1771TH/readings?_sorted
INFO 2025-03-10 03:40:16,015 basehttp "GET /readings/1771TH/ HTTP/1.1" 200 143426
